/* WALL-AP */

#define BOARD_PID		"WALL-AP"
#define BOARD_NAME		"WALL-AP"
#define BOARD_DESC		"WALL-AP Wireless Router"
#define BOARD_VENDOR_NAME	"WALL-AP"
#define BOARD_VENDOR_URL	"http://www.wallap.com/"
#define BOARD_MODEL_URL		"http://www.wallap.com/"
#define BOARD_BOOT_TIME		25
#define BOARD_FLASH_TIME	120
#define BOARD_GPIO_BTN_RESET	1
#undef BOARD_GPIO_BTN_WPS
#undef  BOARD_GPIO_LED_ALL	 
#define BOARD_GPIO_LED_WIFI	72
#undef BOARD_GPIO_LED_POWER	
#undef  BOARD_GPIO_LED_LAN
#undef  BOARD_GPIO_LED_WAN
#undef BOARD_GPIO_LED_USB 
#undef  BOARD_GPIO_LED_ROUTER
#undef  BOARD_GPIO_PWR_USB
#define BOARD_HAS_5G_11AC	0
#define BOARD_NUM_ANT_5G_TX	0
#define BOARD_NUM_ANT_5G_RX	0
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_EPHY	2
#define BOARD_NUM_ETH_LEDS	0
#define BOARD_HAS_EPHY_L1000	0
#define BOARD_HAS_EPHY_W1000	0
